# Generated by Django 2.2.1 on 2019-05-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('check_in_time', models.DateTimeField()),
                ('room_id', models.IntegerField()),
                ('model', models.CharField(max_length=10)),
                ('operation', models.CharField(max_length=15)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('start_temp', models.FloatField()),
                ('end_temp', models.FloatField()),
                ('wind', models.CharField(max_length=10)),
                ('fee_rate', models.FloatField()),
                ('fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_id', models.IntegerField()),
                ('switch', models.IntegerField()),
                ('time', models.IntegerField()),
                ('fee', models.FloatField()),
                ('schedule', models.IntegerField()),
                ('change_temp', models.IntegerField()),
                ('change_wind', models.IntegerField()),
            ],
        ),
    ]
